# Generated by Django 2.2.16 on 2022-03-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220324_1202'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_following',
        ),
    ]
